### ISSUE TITLE
Test regression with chardet 6.0.0

### ISSUE THREAD

**Issue by musicinmybrain** [ebook-utils/css-parser#14]
The `chardet` package has just released [version 6.0.0](https://github.com/chardet/chardet/releases/tag/6.0.0), a major update with a new “encoding era” concept and a number of other significant changes.

This leads to a regression in the tests:

```
$ git clone https://github.com/ebook-utils/css-parser.git
$ cd css-parser
$ uv venv
$ . .venv/bin/activate
(css-parser) $ uv pip install -e .
(css-parser) $ uv pip install chardet
(css-parser) $ ./run_tests.py
[…]
======================================================================
ERROR: test_tryEncodings (css_parser_tests.test_encutils.AutoEncodingTestCase.test_tryEncodings)
encutils.tryEncodings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/src/forks/css-parser/css_parser_tests/test_encutils.py", line 210, in test_tryEncodings
    self.assertEqual(exp.lower(), encutils.tryEncodings(test).lower())
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

----------------------------------------------------------------------
Ran 384 tests in 1.648s

FAILED (errors=1)
```

The difference here is in:

https://github.com/ebook-utils/css-parser/blob/f958db93fb45dc89ce92fb845d7c668fe1c47940/css_parser_tests/test_encutils.py#L198

Testing in a virtualenv with `chardet` 5.2.0:

```
>>> chardet.detect('€'.encode('windows-1252'))
{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}
```

…but with `chardet` 6.0.0:

```
>>> chardet.detect('€'.encode('windows-1252'))
{'encoding': None, 'confidence': 0.0, 'language': None}
```

**Comment by musicinmybrain** [comment]
Thanks for having a look at this!

As of 060e3cd136bdbe4510c2e43cc74bfb926f02191f, the tests now pass with `chardet` 6.0.0, but the new test cases merged into the `tests` list from the unused `except ImportError` branch don’t work with `chardet` 5.2.0.

https://github.com/ebook-utils/css-parser/blob/060e3cd136bdbe4510c2e43cc74bfb926f02191f/css_parser_tests/test_encutils.py#L198-L199

```
(css-parser) $ uv pip install chardet==5.2.0
(css-parser) $ ./run_tests.py
...............................................................................................................................................................................................................................................................................................................................................................................................F
======================================================================
FAIL: test_tryEncodings (css_parser_tests.test_encutils.AutoEncodingTestCase.test_tryEncodings)
encutils.tryEncodings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/src/forks/css-parser/css_parser_tests/test_encutils.py", line 206, in test_tryEncodings
    self.assertEqual(exp.lower(), encutils.tryEncodings(test).lower())
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'iso-8859-1' != 'maccyrillic'
- iso-8859-1
+ maccyrillic


----------------------------------------------------------------------
Ran 384 tests in 0.916s

FAILED (failures=1)
```

**Comment by kovidgoyal** [comment]
Ah, right. I think I will just remove that test. This code isnt actually used anywhere in calibre anymore anyway.

**Comment by dougmassay** [comment]
Kevin and I may need to check what parts we use internally in Sigil. We're ok with our bundles (since they use chardet 5.2.0). But Linux distros that use that use external python pieces for Sigil may be affected. Especially cutting edge distros like Arch.

**Comment by kovidgoyal** [comment]
Yeah, the only reason it is still included in calibre is that html5lib
uses it and that in turn is used by some very old/marginal code.

**Comment by kevinhendricks** [comment]
Already posted a copy of this bug to chardets github.  I think they have gone to more state machine approaches and they have not tested strings with single characters.  In my quick test in a standalone python env, basic detect still works for longer strings.

That said they have now broken encodings iinto eras, and you can select from among the most common, to the quite esoteric with a new era parameter to detect.

Win 1252 is supposed to be in the default detect state.  Either way, the chardet devs now know of this change in behaviour.

**Comment by kevinhendricks** [comment]
See the dev's response here:

https://github.com/chardet/chardet/issues/317

**Comment by kovidgoyal** [comment]
Seems like they are now using statistical models which means tests, especially with short strings, arent going to be stable going forward. So I am good with just removing the test in css_parser, which I have done. From a brief look into the code the only code path I could find that actually uses this in css_parser is downloading html from a URL and parsing the CSS in it. If you want to restore the tests, feel free to do so, but we will then need short strings that work with 5.x and 6.x

**Comment by kevinhendricks** [comment]
I am okay with dropping the tests.  chardet basic detect functionality still works but only on longer strings.  Sigil uses its own internal detection routine, but sigil_bs4 still uses it in its dammit.py code but as I said, basic larger sample detection still works.

I will look into making sigil_bs4 code tolerant enough to handle None returns as encoding guess from any calls to detect in that code.   Uses of non-utf-8 code are getting rarer by the day.

Update:
Luckily the chardet_dammit function in sigil_bs4 already handles a None return for  an encoding guess, so Sigil is good to go.
